//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.27 at 08:45:43 PM EET 
//


package tr.gov.uab.unet.spring_boot_soap_ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tr.gov.uab.unet.spring_boot_soap_ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tr.gov.uab.unet.spring_boot_soap_ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetYbsIlByIdRequest }
     * 
     */
    public GetYbsIlByIdRequest createGetYbsIlByIdRequest() {
        return new GetYbsIlByIdRequest();
    }

    /**
     * Create an instance of {@link GetYbsIlByIdResponse }
     * 
     */
    public GetYbsIlByIdResponse createGetYbsIlByIdResponse() {
        return new GetYbsIlByIdResponse();
    }

    /**
     * Create an instance of {@link YbsIlDto }
     * 
     */
    public YbsIlDto createYbsIlDto() {
        return new YbsIlDto();
    }

    /**
     * Create an instance of {@link AddYbsIlResponse }
     * 
     */
    public AddYbsIlResponse createAddYbsIlResponse() {
        return new AddYbsIlResponse();
    }

    /**
     * Create an instance of {@link YbsIlStatus }
     * 
     */
    public YbsIlStatus createYbsIlStatus() {
        return new YbsIlStatus();
    }

    /**
     * Create an instance of {@link GetAllYbsIlResponse }
     * 
     */
    public GetAllYbsIlResponse createGetAllYbsIlResponse() {
        return new GetAllYbsIlResponse();
    }

    /**
     * Create an instance of {@link AddYbsIlRequest }
     * 
     */
    public AddYbsIlRequest createAddYbsIlRequest() {
        return new AddYbsIlRequest();
    }

    /**
     * Create an instance of {@link UpdateYbsIlRequest }
     * 
     */
    public UpdateYbsIlRequest createUpdateYbsIlRequest() {
        return new UpdateYbsIlRequest();
    }

    /**
     * Create an instance of {@link DeleteYbsIlResponse }
     * 
     */
    public DeleteYbsIlResponse createDeleteYbsIlResponse() {
        return new DeleteYbsIlResponse();
    }

    /**
     * Create an instance of {@link GetAllYbsIlRequest }
     * 
     */
    public GetAllYbsIlRequest createGetAllYbsIlRequest() {
        return new GetAllYbsIlRequest();
    }

    /**
     * Create an instance of {@link DeleteYbsIlRequest }
     * 
     */
    public DeleteYbsIlRequest createDeleteYbsIlRequest() {
        return new DeleteYbsIlRequest();
    }

    /**
     * Create an instance of {@link UpdateYbsIlResponse }
     * 
     */
    public UpdateYbsIlResponse createUpdateYbsIlResponse() {
        return new UpdateYbsIlResponse();
    }

}
