//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.27 at 08:45:43 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://unet.uab.gov.tr/spring-boot-soap-ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tr.gov.uab.unet.spring_boot_soap_ws;
